// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// array_w_mean
NumericVector array_w_mean(arma::cube array, DataFrame scheme);
RcppExport SEXP _nemomedusR_array_w_mean(SEXP arraySEXP, SEXP schemeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type array(arraySEXP);
    Rcpp::traits::input_parameter< DataFrame >::type scheme(schemeSEXP);
    rcpp_result_gen = Rcpp::wrap(array_w_mean(array, scheme));
    return rcpp_result_gen;
END_RCPP
}
// emptyRcpp
LogicalMatrix emptyRcpp(arma::cube a);
RcppExport SEXP _nemomedusR_emptyRcpp(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::cube >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(emptyRcpp(a));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nemomedusR_array_w_mean", (DL_FUNC) &_nemomedusR_array_w_mean, 2},
    {"_nemomedusR_emptyRcpp", (DL_FUNC) &_nemomedusR_emptyRcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_nemomedusR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
